project:
  type: website
  output-dir: docs

execute:
  eval: false          # 禁止执行代码
  enabled: false       # 完全禁用执行功能
  freeze: true         # 冻结计算结果
  error: false         # 不显示错误
  warning: false       # 不显示警告
  echo: true          # 显示代码
  include: true       # 包含代码块
  cache: false        # 禁用缓存

website:
  title: ""
  search: false
  navbar:
    background: "#40E0D0"
    left:
      - href: index.qmd
        text: Index
      - href: about.qmd
        text: About Me
      - href: homework.qmd
        text: Homework
      - href: practice.qmd
        text: Practice
      - href: lab.qmd
        text: Lab

format:
  html:
    theme: cosmo
    css: styles.css